# Site settings
title: Faccia a Faccia
email: your-email@domain.com
url: https://example.github.io
description: "Tu da che parte stai?"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#ffffff'
#  links: '#f7e8c2'
#  links: '#a53860'
  links: '#ffffff'
  background: '#018fa4'
#  background: '#1586bf'
#  background: '#527b89'
#  background: '#ed2e38'
#  background: '#056294'
   
# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
